name: Linters

on:
  push:
    branches:
      - main
      - version-15
  pull_request:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Black (Frappe)
        run: pip install git+https://github.com/frappe/black.git

      - name: Run Black (Frappe)
        run: black --check .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettify code
        uses: rutajdash/prettier-cli-action@v1.0.0
        with:
          config_path: ./.prettierrc.js
          ignore_path: ./.prettierignore

      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{ steps.prettier-run.outputs.prettier_output }}" >> $GITHUB_OUTPUT
